version: '3.6'
services:
  postgres:
    image: postgres:12
    restart: always
    volumes:
      - db_type:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
    ports:
      - '5432:5432'
volumes:
  db_type:
