name: cron-remotive

on:
  # "Scheduled workflows run on the latest commit on the default or base branch."
  # — https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#schedule
  schedule:
    # (see https://crontab.guru)
    - cron: '15,45,53,55 * * * *'
jobs:
  remotive:
    env:
      APP_URL: ${{ secrets.APP_URL }}
    runs-on: ubuntu-latest
    steps:
      - name: cURL request
        if: ${{ env.APP_URL }}
        run: |
          curl '${{ secrets.APP_URL }}/api/trpc/cron.pull?batch=1' \
           -H 'content-type: application/json' \
           --data-raw '{"0":{"json":"remotive"}}' \
           --fail
