name: E2E-testing
on: [push]
jobs:
  e2e:
    env:
      ALGOLIA_ADMIN_KEY: ${{ secrets.CI_ALGOLIA_ADMIN_KEY }}
      ALGOLIA_APP_KEY: HL0PBWJ0L2
      ALGOLIA_SEARCH_KEY: ${{ secrets.CI_ALGOLIA_SEARCH_KEY }}
      DATABASE_URL: postgresql://postgres:@localhost:5432/trpcdb
      GITHUB_CI: 1
      NODE_ENV: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['14.x']
        os: [ubuntu-latest]
    services:
      postgres:
        image: postgres:12.1
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: trpcdb
        ports:
          - 5432:5432
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - uses: microsoft/playwright-github-action@v1

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - run: yarn build-vercel
      - run: | 
        yarn start &
        npx wait-port http://:3000/api/trpc/algolia.reindex --timeout 10000
        lsof -ti:3000 | xargs kill -9

      - run: yarn lint

      - run: yarn test-start
      - run: yarn test-dev
